CREATE DATABASE REGISTRO_DE_VISITAS

USE REGISTRO_DE_VISITAS
GO

CREATE TABLE USUARIOS(
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
CODIGO_USUARIO AS ('USER'+RIGHT('00'+CONvERT(VARCHAR, ID),(2))),
NOMBRE VARCHAR(30),
APELLIDO VARCHAR(50),
FECHA_NACIMIENTO DATETIME,
PERMISOS VARCHAR(15),
USERNAME VARCHAR(30) UNIQUE,
PASSWORD VARCHAR(30),
)


SELECT * FROM USUARIOS

INSERT INTO USUARIOS VALUES('ADMIN', 'ADMIN', '01-01-2000', 'ADMINISTRATOR', 'ADMIN', 'ADMIN01')
INSERT INTO USUARIOS VALUES('GENERAL', 'GENERAL', '01-30-2000', 'GENERAL', 'GENERAL', 'GENERAL01')


CREATE PROC SP_VALIDAR_USUARIO
@USERNAME VARCHAR(30),
@PASSWORD VARCHAR(30)
AS
SELECT USERNAME, PASSWORD FROM USUARIOS
WHERE USERNAME = @USERNAME AND PASSWORD = @PASSWORD
GO

--EXEC SP_VALIDAR_USUARIO @USERNAME ='ADMIN', @PASSWORD = 'ADMIN01'
















CREATE TABLE EDIFICIOS(
ID INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE VARCHAR(30)
)

INSERT INTO EDIFICIOS VALUES('EDIFIO #1')
INSERT INTO EDIFICIOS VALUES('EDIFIO #2')
INSERT INTO EDIFICIOS VALUES('EDIFIO #3')
INSERT INTO EDIFICIOS VALUES('EDIFIO #4')

SELECT * FROM EDIFICIOS


CREATE TABLE AULAS(
ID INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE VARCHAR(10)
)

INSERT INTO AULAS VALUES('1A')
INSERT INTO AULAS VALUES('1B')
INSERT INTO AULAS VALUES('1C')
INSERT INTO AULAS VALUES('1D')
INSERT INTO AULAS VALUES('2A')
INSERT INTO AULAS VALUES('2B')
INSERT INTO AULAS VALUES('2C')
INSERT INTO AULAS VALUES('2D')
INSERT INTO AULAS VALUES('3A')
INSERT INTO AULAS VALUES('3B')
INSERT INTO AULAS VALUES('3C')
INSERT INTO AULAS VALUES('3D')
INSERT INTO AULAS VALUES('4A')
INSERT INTO AULAS VALUES('4B')
INSERT INTO AULAS VALUES('4C')
INSERT INTO AULAS VALUES('4D')

SELECT * FROM AULAS


CREATE TABLE VISITA(
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
VISITORCODE AS ('USER'+RIGHT('00'+CONvERT(VARCHAR, ID),(2))),
NOMBRE VARCHAR(30),
APELLIDO VARCHAR(50),
CAREER VARCHAR(20),
EDIFICIO INT NOT NULL FOREIGN KEY REFERENCES EDIFICIOS(ID),
HORA_ENTRADA DATETIME,
HORA_SALIDA DATETIME,
MOTIVO VARCHAR(100),
AULA INT NOT NULL FOREIGN KEY REFERENCES AULAS(ID)
)



SELECT * FROM VISITA

INSERT INTO VISITA VALUES('ENMANUEL', 'MENDEZ', 'SOFTWARE', 1, '12:55', '1:30', 'TOCARLE LOS COJONES AL PROFESOR', 2)
INSERT INTO VISITA VALUES('NARUTO', 'UZUMAKI', 'MECATRONICA', 1, '22:00', '3:30', 'TOMAR EXAMEN', 5)


SELECT VISITA.ID, VISITA.VISITORCODE, VISITA.NOMBRE, VISITA.CAREER, 
EDIFICIOS.NOMBRE AS EDIFICIO, VISITA.HORA_ENTRADA, VISITA.HORA_SALIDA, VISITA.MOTIVO, AULAS.NOMBRE AS AULA
FROM VISITA
INNER JOIN EDIFICIOS ON VISITA.EDIFICIO = EDIFICIOS.ID
INNER JOIN AULAS ON VISITA.AULA = AULAS.ID