CREATE DATABASE REGISTRO_DE_VISITAS
Go

USE REGISTRO_DE_VISITAS
GO

--CREAR TABLA USUARIO
CREATE TABLE USUARIOS(
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
CODIGO_USUARIO AS ('USER'+RIGHT('00'+CONvERT(VARCHAR, ID),(2))),
NOMBRE VARCHAR(30),
APELLIDO VARCHAR(50),
FECHA_NACIMIENTO DATETIME,
PERMISOS VARCHAR(15),
USERNAME VARCHAR(30) UNIQUE,
PASSWORD VARCHAR(30),
)
GO

--CREAR TABLA EDIFICIOS
CREATE TABLE EDIFICIOS(
ID INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE VARCHAR(30)
)

--CREAR TABLA AULAS
CREATE TABLE AULAS(
ID INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE VARCHAR(10)
)

--CREAR TABLA VISITA
CREATE TABLE VISITA(
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
VISITORCODE AS ('USER'+RIGHT('00'+CONvERT(VARCHAR, ID),(2))),
NOMBRE VARCHAR(30),
APELLIDO VARCHAR(50),
CAREER VARCHAR(20),
CORREO VARCHAR(100),
EDIFICIO INT NOT NULL FOREIGN KEY REFERENCES EDIFICIOS(ID),
AULA INT NOT NULL FOREIGN KEY REFERENCES AULAS(ID),
HORA_ENTRADA DATETIME,
HORA_SALIDA DATETIME,
MOTIVO VARCHAR(100),
)

--INSERTAR USUARIO ADMINISTRADOR
INSERT INTO USUARIOS VALUES('ADMIN', 'ADMIN', '01-01-2000', 'ADMINISTRATOR', 'ADMIN', 'ADMIN01')

--INSERTAR USUARIO GENERAL
INSERT INTO USUARIOS VALUES('GENERAL', 'GENERAL', '01-30-2000', 'GENERAL', 'GENERAL', 'GENERAL01')

--INSERTAR EDIFIOS
INSERT INTO EDIFICIOS VALUES('EDIFIO #1')
INSERT INTO EDIFICIOS VALUES('EDIFIO #2')
INSERT INTO EDIFICIOS VALUES('EDIFIO #3')
INSERT INTO EDIFICIOS VALUES('EDIFIO #4')

--INSERTAR AULAS
INSERT INTO AULAS VALUES('1A')
INSERT INTO AULAS VALUES('1B')
INSERT INTO AULAS VALUES('1C')
INSERT INTO AULAS VALUES('1D')
INSERT INTO AULAS VALUES('2A')
INSERT INTO AULAS VALUES('2B')
INSERT INTO AULAS VALUES('2C')
INSERT INTO AULAS VALUES('2D')
INSERT INTO AULAS VALUES('3A')
INSERT INTO AULAS VALUES('3B')
INSERT INTO AULAS VALUES('3C')
INSERT INTO AULAS VALUES('3D')
INSERT INTO AULAS VALUES('4A')
INSERT INTO AULAS VALUES('4B')
INSERT INTO AULAS VALUES('4C')
INSERT INTO AULAS VALUES('4D')


--INSERTAR VISITAS
INSERT INTO VISITA VALUES('ENMANUEL', 'MENDEZ', 'SOFTWARE', 'ENMANUEL@GMAIL.COM', 1, 2, '12:55', '1:30', 'TOCARLE LOS COJONES AL PROFESOR')
INSERT INTO VISITA VALUES('NARUTO', 'UZUMAKI', 'MECATRONICA', 'NARUTO@GMAIL.COM', 1, 2, '22:00', '3:30', 'TOMAR EXAMEN')


--PROCEDIMIENTO VALIDAR USUARIOS
CREATE PROC SP_VALIDAR_USUARIO
@USERNAME VARCHAR(30),
@PASSWORD VARCHAR(30)
AS
SELECT USERNAME, PASSWORD FROM USUARIOS
WHERE USERNAME = @USERNAME AND PASSWORD = @PASSWORD
GO


--PROCEDIMIENTO BUSCAR USUARIOS
CREATE PROC SP_BUSCARUSUARIO
@BUSCARNOMBRE VARCHAR(30)
AS
SELECT * FROM USUARIOS
WHERE NOMBRE LIKE @BUSCARNOMBRE + '%'

EXEC SP_BUSCARUSUARIO @BUSCARNOMBRE = ''




--PROCEDIMIENTO BUSCAR VISITAS POR EDIFICIO
CREATE PROC SP_BUSCARVISITAEDIFICIO
@BUSCAREDIFICIO VARCHAR(30)
AS
SELECT VISITA.ID, VISITA.VISITORCODE, VISITA.NOMBRE, VISITA.APELLIDO, VISITA.CAREER, VISITA.CORREO,
EDIFICIOS.NOMBRE AS EDIFICIO, AULAS.NOMBRE AS AULA, VISITA.HORA_ENTRADA, VISITA.HORA_SALIDA, VISITA.MOTIVO,
VISITA.EDIFICIO, VISITA.AULA
FROM VISITA
INNER JOIN EDIFICIOS ON VISITA.EDIFICIO = EDIFICIOS.ID
INNER JOIN AULAS ON VISITA.AULA = AULAS.ID
WHERE VISITA.EDIFICIO LIKE @BUSCAREDIFICIO + '%'


--PROCEDIMIENTO BUSCAR VISITAS POR AULA
CREATE PROC SP_BUSCARVISITAAULA
@BUSCARAULA VARCHAR(30)
AS
SELECT VISITA.ID, VISITA.VISITORCODE, VISITA.NOMBRE, VISITA.APELLIDO, VISITA.CAREER, VISITA.CORREO,
EDIFICIOS.NOMBRE AS EDIFICIO, AULAS.NOMBRE AS AULA, VISITA.HORA_ENTRADA, VISITA.HORA_SALIDA, VISITA.MOTIVO,
VISITA.EDIFICIO, VISITA.AULA
FROM VISITA
INNER JOIN EDIFICIOS ON VISITA.EDIFICIO = EDIFICIOS.ID
INNER JOIN AULAS ON VISITA.AULA = AULAS.ID
WHERE AULAS.NOMBRE LIKE @BUSCARAULA + '%'


--PROCEDIMIENTO BUSCAR VISITAS POR NOMBRE
CREATE PROC SP_BUSCARVISITANOMBRE
@BUSCARNOMBRE VARCHAR(30)
AS
SELECT VISITA.ID, VISITA.VISITORCODE, VISITA.NOMBRE, VISITA.APELLIDO, VISITA.CAREER, VISITA.CORREO,
EDIFICIOS.NOMBRE AS EDIFICIO, AULAS.NOMBRE AS AULA, VISITA.HORA_ENTRADA, VISITA.HORA_SALIDA, VISITA.MOTIVO,
VISITA.EDIFICIO, VISITA.AULA
FROM VISITA
INNER JOIN EDIFICIOS ON VISITA.EDIFICIO = EDIFICIOS.ID
INNER JOIN AULAS ON VISITA.AULA = AULAS.ID
WHERE VISITA.NOMBRE LIKE @BUSCARNOMBRE + '%'


--PROCEDIMIENTO INSERTAR VISITAS
CREATE PROC SP_INSERTARVISITA
@NOMBRE VARCHAR(30),
@APELLIDO VARCHAR(50),
@CAREER VARCHAR(20),
@CORREO VARCHAR(100),
@EDIFICIO INT,
@AULA INT,
@HORA_ENTRADA DATETIME,
@HORA_SALIDA DATETIME,
@MOTIVO VARCHAR(100)
AS
INSERT INTO VISITA VALUES(@NOMBRE, @APELLIDO, @CAREER, @CORREO, @EDIFICIO, @AULA, @HORA_ENTRADA, @HORA_SALIDA, @MOTIVO)
GO


--PROCEDIMIENTO EDITAR VISITA
CREATE PROC SP_EDITARVISITA
@ID INT,
@NOMBRE VARCHAR(30),
@APELLIDO VARCHAR(50),
@CAREER VARCHAR(20),
@CORREO VARCHAR(100),
@EDIFICIO INT,
@AULA INT,
@HORA_ENTRADA DATETIME,
@HORA_SALIDA DATETIME,
@MOTIVO VARCHAR(100)
AS
UPDATE VISITA SET NOMBRE = @NOMBRE, APELLIDO = @APELLIDO, CAREER = @CAREER, CORREO = @CORREO, EDIFICIO = @EDIFICIO,
AULA = @AULA, HORA_ENTRADA = @HORA_ENTRADA, HORA_SALIDA = @HORA_SALIDA, MOTIVO = @MOTIVO
WHERE ID = @ID


--PROCEDIMIENTO ELIMINAR VISITA
CREATE  PROC SP_ELIMINARVISITA
@ID INT
AS
DELETE VISITA
WHERE ID = @ID
GO





--PROCEDURE CARGAREDIFICIOS
CREATE PROC SP_CARGAREDIFICIOS
AS
SELECT * FROM EDIFICIOS
GO





--PROCEDURE CARGARAULA
CREATE PROC SP_CARGARAULA
AS
SELECT * FROM AULAS
GO



