CREATE DATABASE VISIT_REGISTRATOR

CREATE DATABASE VISITOR_REGISTRATION
GO

USE VISITOR_REGISTRATION
GO

CREATE TABLE USERS(
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
USERCODE AS ('USER'+RIGHT('00'+CONvERT(VARCHAR, ID),(2))),
NAME VARCHAR(30),
LASTNAME VARCHAR(50),
PERMISSION VARCHAR(15),
USERNAME VARCHAR(30),
PASSWORD VARCHAR(30),
)

SELECT * FROM USERS

INSERT INTO USERS VALUES('ADMIN', 'ADMIN', 'ADMINISTRATOR', 'ADMIN', 'ADMIN01')
INSERT INTO USERS VALUES('GENERAL', 'GENERAL', 'GENERAL', 'GENERAL', 'GENERAL01')
